### ISSUE TITLE
Ajuste do Loader

### ISSUE THREAD

**Issue by oliveiralex** [insanniity/github-user-search#1]
Olá Cleydson, tudo bem?

Sua tarefa foi aceita, parabéns! Apenas gostaria de apontar um possível bug que está ocorrendo ao exibir o Loader ao tentar buscar os dados de um usuário do gitHub na primeira requisição. Fiz o seguinte caminho:

1. Coloquei os dados do usuário "acenelio" e então aparece uma mensagem "usuário não encontrado", quando que o correto seria carregar o Loader. (Imagem a seguir)

![Captura de tela de 2021-02-10 11-27-04](https://user-images.githubusercontent.com/2441741/107524472-912e6200-6b94-11eb-8732-87a8bf311576.png)

2. Em seguida, os dados do usuário carregam corretamente e após isto, caso eu coloque os dados de qualquer usuário, o Loader está sendo exibido corretamente. 

Ao que me pareceu, este evento acontece somente na primeira requisição. Peço que você verifique certinho como você você estruturou o Loader para a primeira requisição.

Atenciosamente

**Comment by insanniity** [comment]
@oliveiralex corrigido em [`#76432fdb99755112bdaf87c53b0dff82a961a73f`](https://github.com/insanniity/github-user-search/commit/76432fdb99755112bdaf87c53b0dff82a961a73f)
